version: "3.3"
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8001:8001
    image: app:app
    container_name: deep_link
    command: python manage.py runserver 0.0.0.0:8001